=== MarioPalacios569/Palacios-Moreno-Mario/XML/Bloque2_XSD/ACT_Tema/Ej5.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="datos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="persona" maxOccurs="unbounded">
                    <xs:complexType mixed="true">
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="apellido" type="xs:string"/>
                            <xs:element name="DNI" type="xs:string"/>
                            <xs:element name="comentario" type="xs:string"/>
                            <xs:element name="pago">
                                <xs:complexType mixed="true">
                                    <xs:sequence>
                                        <xs:element name="numero" type="xs:string" />  
                                    </xs:sequence>
                                    <xs:attribute name="tipo" type="xs:string" use="required"/>  
                                </xs:complexType>
                            </xs:element>
                           <xs:element name="nota" maxOccurs="unbounded">
                                <xs:simpleType>
                                    <xs:restriction base="xs:int">
                                        <xs:minInclusive value="0"/>
                                        <xs:maxInclusive value="10"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:integer" use="required"/>
                        <xs:attribute name="fechanac" type="xs:date" use="optional"/>
                    </xs:complexType>
                </xs:element>  
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== MarioPalacios569/Palacios-Moreno-Mario/XML/Bloque2_XSD/ACT_Tema/EJ5.xml
<?xml version="1.0" encoding="UTF-8"?>
<datos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Ej5.xsd">
    <persona id="1" fechanac="1990-01-01">
        <nombre>Fernando</nombre>
        <apellido>Lopez</apellido>
        <DNI>5673893L</DNI>
        <comentario>Breve descripción de la persona</comentario>
        <pago tipo="tarjeta">
            <numero>1234567890123456</numero>
        </pago>
        <nota>7</nota>
    </persona>

    <persona id="2">
        <nombre>Maria</nombre>
        <apellido>Gomez</apellido>
        <DNI>9876543P</DNI>
        <comentario>Otra descripción</comentario>
        <pago tipo="transferencia">
            <numero>ES9121000418450200051332</numero>
        </pago>
        <nota>10</nota>
    </persona>
</datos>
